### PR TITLE
remove apt recipe

### LINKED ISSUE #66: apt recipe still included
[The repo recipe](https://github.com/sensu/uchiwa-chef/blob/master/recipes/repo.rb#L28) still tries to `include_recipe 'apt'`. I suspect this got missed during #65? I can send you a tiny PR if you like!

### PR DESCRIPTION
**Pull request by bleything**
### Description

Removes an errant `include_recipe 'apt'` that was missed during #65.

### Issues Resolved

#66 

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by bleything** [comment]
I was not able to run the test suite due to some issue with my environment. I'm pretty confident in this tiny change though.

**Comment by bleything** [comment]
<3

**Comment by majormoses** [comment]
released: https://supermarket.chef.io/cookbooks/uchiwa/versions/2.0.1

**Comment by bleything** [comment]
Thanks! Confirmed this fixed it for me

**Pull request merged**
