### PR TITLE
bumping up uchiwa version up to 0.7.1

### PR DESCRIPTION
**Pull request by osigida**
uchiwa release: https://github.com/sensu/uchiwa/releases/tag/0.7.1

### CODE REVIEW

**Comment by tas50** [comment]
We should prob go right up to 0.8.1 now

**Comment by osigida** [comment]
@tas50 done.
however, if we wait for another 24 days, the request will be outdated again

**Comment by tas50** [comment]
@amdprophet Any chance we can get a merge here?

**Comment by amdprophet** [comment]
I'll cut a release this morning.

**Pull request merged**
